Mymusic/urls.py
from django.contrib import admin
from django.urls import path,include
import music.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('music.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

music/urls.py
from django.urls import path
from django.conf.urls import url

from .import views

app_name = 'music'

urlpatterns = [


     path('',views.IndexView.as_view(),name= 'index'),
      path('visitor/',views.VisitorView.as_view(),name= 'base-visitor'),
     path('<int:pk>',views.DetailView.as_view(),name='detail'),
    path('register/',views.UserFormView.as_view(),name='register'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('login/',views.LoginView.as_view(),name='login'),
    url('create_album/',views.create_album,name='create_album'),
     path('<int:pk>',views.AlbumUpdate.as_view(),name='album-update'),
     path('favorite/<int:pk>',views.AlbumUpdate.as_view(),name='album-favorite'),
     path('delete/<int:pk>',views.AlbumDelete.as_view(),name='album-delete'),
      path('add/song/', views.SongCreate.as_view(), name='create-song'),
      path('delete/song/<int:pk>',views.SongDelete.as_view(),name='delete-song'),
      path('',views.SongUpdate.as_view(),name='fav_song'),
      path('songs/<filter_by>',views.songs,name='songs'),
]

music/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import Permission, User
from django.conf import settings
# Create your models here.


class Album(models.Model):
    user = models.ForeignKey(User, default=1,on_delete=models.CASCADE)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})


    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    audio_file = models.FileField()
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:index')
    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import  Album

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

class AlbumForm(forms.ModelForm):
    

    class Meta:
        model = Album
        fields = ['artist','album_title','genre','album_logo']


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','password']

music/views.py
from django.urls import reverse
from django.shortcuts import render,get_object_or_404,redirect
#from .models import Music
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
######################################
from django.contrib.auth import authenticate, login,logout
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import FormView,CreateView,UpdateView,DeleteView
from .models import Album
from .models import Song
from django.urls import reverse_lazy
from .forms import UserForm,LoginForm,AlbumForm
from django.db.models import Q
from django.http import  HttpResponseRedirect
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


class IndexView(generic.ListView):

    template_name = 'music/index.html'
    context_object_name = 'all_albums'



    def get(self,request):
        if not request.user.is_authenticated:
            form = LoginForm
            return render(request,'music/login.html',{'form':form})
        else:
            all_albums=Album.objects.filter(user=request.user)
            albums = Album.objects.filter(user=request.user)
            song_result = Song.objects.all()
            query = request.GET.get("q")
            if query:
                albums = albums.filter(
                Q(album_title__icontains=query)|
                Q(artist__icontains=query)
                ).distinct()
                song_result = song_result.filter(
                Q(song_title__icontains=query)
                ).distinct()
                return render(request,'music/index.html',{
                'albums':albums,
                'songs':song_result,
                })
            else:
                return render(request,'music/index.html',{'albums':albums,'all_albums':all_albums})


class VisitorView(View):
    template_name = 'music/base_visitor.html'

    def get(self,request):
        return render(request,'music/base_visitor.html')




class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'



def create_album(request):
    if not request.user.is_authenticated:
        form = LoginForm
        return render(request,'music/login.html',{'form':form})
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if  form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.album_logo = request.FILES['album_logo']
            file_type = album.album_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                'album':album,
                'form':form,
                'error_message':'Image file must be PNG,JPG, or JPEG',
                }
                return render(request,'music/album_form.html',context)
            album.save()
            return render(request,'music/detail.html',{'album':album})
        context = {
        'form':form,
        }
        return render(request,'music/album_form.html',context)





class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

    def post(self,*args,**kwargs):
        self.object = self.get_object()

        if self.object.is_favorite:
            self.object.is_favorite = False
        else:
            self.object.is_favorite = True
        self.object.save()

        return redirect('music:index')

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class SongCreate(CreateView):
    model = Song
    template_name='music/song.html'
    context_object_name='album'
    fields = ['album','audio_file','song_title','is_favorite']

    #def get(self,request,album):
        #return render(request,'music/song.html',{'album':album})

class SongUpdate(UpdateView):
    model = Song
    fields = ['album','file_type','song_title','is_favorite']

    def post(self,*args,**kwargs):
        self.object = self.get_object()

        if self.object.is_favorite:
            self.object.is_favorite = False
        else:
            self.object.is_favorite = True
        self.object.save()

        #return HttpResponseRedirect(self.request.path_info)


class SongDelete(DeleteView):
    model = Song
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})


    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            #cleaned (normalised ) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return User object if credential are correct

            user = authenticate(username=username,password=password)

            if user is not None:
                login(request,user)
                return redirect('music:index')
        return render(request,self.template_name,{'form':form})



class LoginView(FormView):
    content ={}
    content['form'] = LoginForm

    @method_decorator(csrf_exempt)
    def dispatch(self,request,*args,**kwargs):
        return super(LoginView,self).dispatch(request,*args,**kwargs)

    def get(self,request):
        content = {}
        if request.user.is_authenticated:
            return redirect(reverse('music:index'))
        content['form'] = LoginForm
        return render(request,'music/login.html',content)

    def post(self,request):
        content = {}
        username = request.POST['username']
        password = request.POST['password']

        try:
            #users = users.objects.filter()
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect(reverse('music:index'))

        except Exception as e:
            content = {}
            content['form'] = LoginForm
            content['error'] = 'Unable to login with Provided credentials '
            return render('music/login.html',content)

class LogoutView(FormView):
    def get(self,request):
        form = LoginForm
        logout(request)
        return render(request,'music/login.html',{'form':form})


def songs(request,filter_by):
    if not request.user.is_authenticated:
        form = LoginForm
        return render(request,'music/login.html',{'form':form})
    else:
        try:
            song_id = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_id.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_id)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
        except Album.DoesNotExist:
            users_songs = []
        return render(request,'music/song_list.html',{
        'song_list':users_songs,
        'filter_by':filter_by,
        })

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <title>{% block title %}SkyBeat{%endblock%}</title>
     <link rel="shortcut icon" type="image/x-icon" href="{%  static 'music/images/favicon.ico'%}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Tangerine">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>


  <style>

body{
   background-image: url("{%static 'music/images/back01.jpg'%}");
   background-size: cover;
   background-repeat: no-repeat;
   background-position: center;

}

.t_style{
font-family: 'Great Vibes', cursive;
font-size: 25px;
font-style: italic;
font-weight: bold;



}
.bg{
background-color:rgba(7,7,7,0.6);
}
.trans{
  background-color: rgba(255,255,255,0.3);
}
  </style>
  </head>


  <body>



    <nav class="navbar navbar-expand-lg navbar-dark    trans ">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">



      </button>
      <a class="navbar-brand t_style" href="{% url 'music:index'%}">
    <img src="{% static 'music/images/logo.jpg' %}" width="40px">&nbsp;SkyBeat
      </a>

        <ul class="navbar-nav   mr-auto mt-2 mt-lg-0" id="nav">
          <li class="nav-item ">
            <a class="nav-link hv" href="{% url 'music:songs' 'all'%}"><span class="fas fa-music" aria-hidden="true"></span>&nbsp; Song</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'music:index'%}">  <span class="fas fa-compact-disc" aria-hidden="true"></span>&nbsp;  Album</a>
          </li>

      <li class="nav-item ">

        <form class="  navbar-left form-inline my-2 my-lg-0 " role="search" method="get" action="{% url 'music:index'%}">
          <input class="form-control mr-sm-2"  type="search" placeholder="Search" name="q" value="{{request.GET.q}}"aria-label="Search">
          <button class="btn  btn-light  " type="submit">Search</button>
       </form>
     </li>
    </ul>

    <ul class="navbar-nav  navbar-right">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:create_album'%}">  <span class="fas fa-plus" aria-hidden="true"></span>&nbsp; Add Album</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'music:logout'%}"><span class="fas fa-power-off" aria-hidden="true"></span>&nbsp; Logout</a>
      </li>
      {% else %}
      <li class="nav-item ">

        <a class="nav-link" href="{% url 'music:login'%}"><span class="fas fa-login" aria-hidden="true"></span>&nbsp; Login</a>
      </li>
      <li class="nav-item ">

        <a class="nav-link" href="{% url 'music:register'%}"><span class="fas fa-login" aria-hidden="true"></span>&nbsp; Register</a>
      </li>
      {% endif %}


    </ul>

    </nav>


    {% block body %}
    {% endblock %}

  </body>

</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Muiscale{%endblock%}</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Tangerine">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  <style>
body{
   background-image: url("{%static 'music/images/back01.jpg'%}");
   background-size: cover;
   background-repeat: no-repeat;
   background-position: center;

}

.bg-nav{


}
.bg{
background-color:rgba(7,7,7,0.6);
}
.trans{
  background-color: rgba(255,255,255,0.3);
}
  </style>
  </head>

  <body>



    <nav class="navbar navbar-expand-lg navbar-dark   trans ">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Musicale</a>

        <ul class="navbar-nav   mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link hv" href="#"><span class="fas fa-music" aria-hidden="true"></span>&nbsp; Song</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="#">  <span class="fas fa-compact-disc" aria-hidden="true"></span>&nbsp;  Album</a>
          </li>

      <li class="nav-item ">

        <form class="  navbar-left form-inline my-2 my-lg-0 ">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn  btn-light  " type="submit">Search</button>
       </form>
     </li>
    </ul>

    <ul class="navbar-nav  navbar-right">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'music:create_album'%}">  <span class="fas fa-plus" aria-hidden="true"></span>&nbsp; Add Album</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'music:logout'%}"><span class="fas fa-logout" aria-hidden="true"></span>&nbsp; Logout</a>
      </li>

      {% else %}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'music:login'%}"><span class="fas fa-login" aria-hidden="true"></span>&nbsp; Login</a>
      </li>
      {% endif %}


    </ul>

    </nav>


    {% block body %}
    {% endblock %}

  </body>

</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<link href="https://fonts.googleapis.com/css?family=Tangerine&display=swap" rel="stylesheet">
<style>
.cards{
  margin-top:100px;
  margin-left:100px;
}


h1,h2{
  font-family: 'Tangerine', cursive;
  font-style:italic;
  margin-left:10px;
}
.si{
  width:300px;
  min-height:500px;
}
.tb{
  width:800px;
  min-height:100px;
}
.txt_color{
  color:white;
}

.btn_style{
  border-radius:20px ;
  border:none;
  color:white;
  text-align:center;
  background-color:#F55656;
  width:135px;
  height:35px;
  margin-top:10px;
  margin-right:10px;
}
.ac{
  width:240px;
  height:40px;


}

.t_m{
  margin-left:40px;
}
active{
  color:yellow;
}
</style>
<div class=" albums-container container-fluid ">

   <div  style="margin-top:20px;"class= "row">

        <div class="col-sm-4 col-md-3">
          <div class="card bg">


          <div class="card-body">


        <div class="bg">


       <a href="{% url 'music:detail' album.id %}"></a>

             {% if album.album_logo %}
        <img src="{{album.album_logo.url}}"   class="mx-auto d-block"class="img-thumbnail" height="300px"width="300px"class="img-responsive "alt="">
        {%else%}
          <h3>No image To display</h3>
          {%endif%}
        <h1 class="txt_color">{{album.album_title}}</h1>
        <h1 class="txt_color"><small>{{ album.genre}}</small></h1>
        <h2 class="txt_color"><small>{{album.artist}}</small></h2>
        <h3></h3>




</div>
</div>
</div>
</div>


<div class="  bg col-sm-8 col-md-9   ">

  <ul class="nav nav-pills" style="margin-bottom: 10px;">
              <li role="presentation" class="active "><a class=" btn btn-danger btn_style" href="{% url 'music:index'  %}">View All</a></li>
              <li role="presentation" class=""><a class=" btn btn-danger btn_style" href="{% url 'music:create-song'  %}">Add New Song</a></li>
              </ul>

              <div class="card bg">
                <div class="card-body">
                  <div class="bg">
                      <h3 style="color:white;">All Songs</h3>
                      {%if error_message%}
                       {%endif%}
                     <table class="table">
                       <thead class="thead-dark">
                         <tr>
                           <th   class="t_m  txt_color" >Title</th>
                           <th  class="  txt_color">Audio</th>
                           <th   class="  txt_color">Favorite</th>
                           <th  class="  txt_color">Actions</th>
                         </tr>
                       </thead>
                       <tbody>
                         {% for song in album.song_set.all%}
                           <tr >

                             <td class="txt_color">{{ song.song_title }}</td>

                             <td >

                               <audio class="ac"  controls >


                              <source src="{{song.audio_file.url}}" type="audio/mp3">

                              </audio>

                             </td>
                             <td>


                               <a  class="txt_color " href="" class="btn-favorite">
                                 <span class="  fas fa-star {% if song.is_favorite %}active{% endif %}"></span>
                              </a>





                             </td>
                             <td>
                            <form action="{% url 'music:delete-song' song.id %}"  method="post" style="display:inline;">
                              {%csrf_token%}
                              <input type="hidden" name="song_id" value="{{song.id}}"/>
                              <button type="submit" class="btn btn-danger xs">
                             <span class="fas fa-remove"></span> Delete
                              </button>
                            </form>
                             </td>
                           </tr>
                           {% endfor%}
                       </tbody>

                     </table>

                  </div>
                </div>
              </div>

</div>
</div>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<link href="https://fonts.googleapis.com/css?family=Tangerine&display=swap" rel="stylesheet">
<style>


  .btn_style{
    border-radius:20px ;
    border:none;
    color:white;
    text-align:center;
    background-color:#F55656;
    width:160px;
    height:40px;
    margin-top:10px;
  }
.cards{
  margin:20px;

}
.ma{
  margin-bottom:10px;
  margin-left:10px;
}
h2,h4{
  font-family: 'Tangerine', cursive;

  color:white;


}
.bg{
background-color:rgba(7,7,7,0.6);
}
.trans{
  background-color: rgba(255,255,255,0.3);
}
.rc{
  border-radius:25px;
  background-color:#F55656;
}
hover{

}
h3{
  color:white;
  font-size:40px;
  font-family: 'Tangerine', cursive;

  margin-top:10px;

}
.txt_color{
  color:white;
}
.link-color{
  color:white;
}
.link-color:hover{
  color:white;
}
.fav-color{
  color:yellow;
}
.ac{
  width:240px;
  height:40px;


}
.active{
  color:yellow;
  border:orange;
}
</style>
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12 ">
            <h3>{{user.username}}'s Albums</h3>
        </div>

        {% if all_albums %}
            {% for album in all_albums %}



                <div class="cards ">
                    <div class="bg">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}"   class="img-responsive  img-thumbnail"class="mx-auto d-block" height="300px"width="300px">
                        </a>
                        <div class="caption ma">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <div style="">


                            <a href="{% url 'music:detail' album.id %}" class="btn ma btn-danger btn-sm rc" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{%url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button  type="submit" class="btn ma btn-default btn-sm">

                                    <span class="fas fa-trash-alt "></span>
                                </button>
                                  </form>
                                  <form action="{% url 'music:album-favorite' album.id %}" method="post" style="display: inline;">
                                      {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn  ma btn-default btn-sm ">
                                    <span class="fas fa-star {% if album.is_favorite %}active{% endif %}"></span>
                                </button>

                            </form>
                              </div>
                            <!-- Favorite Album -->
                          </div>

                    </div>

                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:create_album'%}">
                  <div class="col-sm-offset-4 col-sm-10">
                     <button type="button" class=" btn_style ">
                       <span class="fas fa-plus"></span>&nbsp; Add an Album
                     </button>

                  </div>

                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="card bg">
                    <div class="card-body">
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th class="txt_color">Song Title</th>
                                    <th class="txt_color">Artist</th>
                                    <th class="txt_color">Audio File</th>
                                    <th class="txt_color">Album</th>
                                    <th class="txt_color">Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td class="txt_color">{{ song.song_title }}</td>
                                        <td class="txt_color">{{ song.album.artist }}</td>
                                        <td>

                                        <audio class="ac"  controls >
                                          <source src="{{song.audio_file.url}}" type="audio/mp3">
                                          </audio>
                                        </td>
                                        <td class="txt_color">
                                            <a   href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{song.album.album_logo.url}}" class="img-responsive" style="width: 30px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a  class="link-color" href="{%url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td >
                                            <a class="fav-color" href="{%url 'music:favorite-song' song.id %}" class="btn-favorite"><span class="fas fa-star "></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

music/templates/music/login.html
{% include 'music/base.html'%}
{% block title %}Login{% endblock %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Tangerine&display=swap" rel="stylesheet">
<style>
  .formclass{



    border-radius: 10px;
    height:580px;
    width:700px;
    margin-left :30px;
    margin-top:10px;
    padding:20px;
    box-shadow: 0 2px 4px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12);

    background-color:rgba(7,7,7,0.6);

  }
  .btn_style{
    border-radius:20px ;
    border:none;
    color:white;
    text-align:center;
    background-color:#F55656;
    width:100px;
    height:30px;
    margin-top:10px;
  }
.tg{
  font-size:40px;
  font-family: 'Tangerine', cursive;
  margin-left:200px;

}
</style>

<div style="margin-top:10px;" class="container-fluid">
<div class="row">
    <div class="col-sm-12 col-md-7 ">
      <div class="panel-body">

        <form class="form-horizontal formclass" role="form" action="" method="post" enctype="multipart/form-data">
            <p class="tg">Login</p>
          {% csrf_token %}
          {% include 'music/form_template.html'%}
          <div class="form-group ">
            <div class="col-sm-offset-4 col-sm-10">
               <button type="submit" class=" btn_style ">Submit</button>

            </div>
            <div class="">
              <small class="text-muted">Don't  Have a Account?
                <a href="{% url 'music:register'%}">Register</a>

              </small>

          </div>
        </form>
      </div>
    </div>
  </div>

</div>